/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desaingui;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class KonverterTemperatur extends javax.swing.JFrame {

    /**
     * Creates new form KonverterTemperatur
     */
    public KonverterTemperatur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        judulDialog = new javax.swing.JLabel();
        besaranAwal = new javax.swing.JLabel();
        satuanAwal = new javax.swing.JLabel();
        labelsamadengan = new javax.swing.JLabel();
        besaranKonversi = new javax.swing.JLabel();
        satuanKonversi = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelCelcius = new javax.swing.JLabel();
        labelUbah = new javax.swing.JLabel();
        inputSuhu = new javax.swing.JTextField();
        temperatur = new javax.swing.JComboBox<>();
        tblKonversi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tempAwal = new javax.swing.JComboBox<>();

        jDialog1.setTitle("result");

        judulDialog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        judulDialog.setText("Hasil Konversi");
        judulDialog.setName("judulDialog"); // NOI18N

        besaranAwal.setText("jLabel1");

        satuanAwal.setText("jLabel1");

        labelsamadengan.setText("=");

        besaranKonversi.setText("jLabel1");

        satuanKonversi.setText("jLabel1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(judulDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(besaranAwal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(satuanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(besaranKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(satuanKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(judulDialog)
                .addGap(69, 69, 69)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(besaranAwal)
                    .addComponent(satuanAwal)
                    .addComponent(labelsamadengan)
                    .addComponent(besaranKonversi)
                    .addComponent(satuanKonversi))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabel1.setText("output error");

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("temperature converter");

        labelCelcius.setText("Suhu");
        labelCelcius.setName("labelCelcius"); // NOI18N

        labelUbah.setText("Ubah ke");
        labelUbah.setName("labelUbah"); // NOI18N

        inputSuhu.setName("inputSuhu"); // NOI18N
        inputSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuhuActionPerformed(evt);
            }
        });

        temperatur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Kelvin", "Reamur", "Fahrenheit" }));
        temperatur.setName("temperatur"); // NOI18N

        tblKonversi.setText("Konversi");
        tblKonversi.setName("tblKonversi"); // NOI18N
        tblKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKonversiActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        labelJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelJudul.setText("Konversi Temperatur");
        labelJudul.setAlignmentX(5.0F);
        labelJudul.setAlignmentY(5.0F);
        labelJudul.setName("label judul"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Gambar\\Saved Pictures\\pngegg (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        tempAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Kelvin", "Reamur", "Fahrenheit" }));
        tempAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempAwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCelcius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblKonversi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(temperatur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tempAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblKonversi)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKonversiActionPerformed
        String temp = temperatur.getSelectedItem().toString();
        String suhuAwal = tempAwal.getSelectedItem().toString();
        double hitung = 0;
        String satuan = null;
        
        if (suhuAwal.equals("Celcius")&& temp.equals("Fahrenheit")){
            double c = Double.parseDouble(inputSuhu.getText());
            double f = (double)(c * 9/5 + 32);
            
            besaranAwal.setText(String.valueOf(c));
            satuanAwal.setText("°C");
            besaranKonversi.setText(String.valueOf(f));
            satuanKonversi.setText("°F");
        }
        if (suhuAwal.equals("Celcius")&& temp.equals("Kelvin")){
            double c = Double.parseDouble(inputSuhu.getText());
            double k = (double)(c + 273);
            
            besaranAwal.setText(String.valueOf(c));
            satuanAwal.setText("°C");
            besaranKonversi.setText(String.valueOf(k));
            satuanKonversi.setText("°K");
        }
        if (suhuAwal.equals("Celcius")&& temp.equals("Reamur")){
            double c = Double.parseDouble(inputSuhu.getText());
            double r = (double)(c * 4/5);
            
            besaranAwal.setText(String.valueOf(c));
            satuanAwal.setText("°C");
            besaranKonversi.setText(String.valueOf(r));
            satuanKonversi.setText("°R");
        }
        if (suhuAwal.equals("Reamur")&& temp.equals("Celcius")){
            double r = Double.parseDouble(inputSuhu.getText());
            double c = (double)(r * 5/4);
            
            besaranAwal.setText(String.valueOf(r));
            satuanAwal.setText("°R");
            besaranKonversi.setText(String.valueOf(c));
            satuanKonversi.setText("°C");
        }
        if (suhuAwal.equals("Reamur")&& temp.equals("Fahrenheit")){
            double r = Double.parseDouble(inputSuhu.getText());
            double f = (double)(r * 9/4 + 32);
            
            besaranAwal.setText(String.valueOf(r));
            satuanAwal.setText("°R");
            besaranKonversi.setText(String.valueOf(f));
            satuanKonversi.setText("°F");
        }
        if (suhuAwal.equals("Reamur")&& temp.equals("Kelvin")){
            double r = Double.parseDouble(inputSuhu.getText());
            double k = (double)(r * 5/4 + 273);
            
            besaranAwal.setText(String.valueOf(r));
            satuanAwal.setText("°R");
            besaranKonversi.setText(String.valueOf(k));
            satuanKonversi.setText("°K");
        }
        if (suhuAwal.equals("Fahrenheit")&& temp.equals("Celcius")){
            double f = Double.parseDouble(inputSuhu.getText());
            double c = (double)(5/9*(f-32));
            
            besaranAwal.setText(String.valueOf(f));
            satuanAwal.setText("°F");
            besaranKonversi.setText(String.valueOf(c));
            satuanKonversi.setText("°C");
        }
        if (suhuAwal.equals("Fahrenheit")&& temp.equals("Reamur")){
            double f = Double.parseDouble(inputSuhu.getText());
            double r = (double)(4/9 *(f - 32));
            
            besaranAwal.setText(String.valueOf(f));
            satuanAwal.setText("°F");
            besaranKonversi.setText(String.valueOf(r));
            satuanKonversi.setText("°R");
        }
        if (suhuAwal.equals("Fahrenheit")&& temp.equals("Kelvin")){
            double f = Double.parseDouble(inputSuhu.getText());
            double k = (double)(5/9 *(f-32)+ 273);
            
            besaranAwal.setText(String.valueOf(f));
            satuanAwal.setText("°F");
            besaranKonversi.setText(String.valueOf(k));
            satuanKonversi.setText("°K");
        }
        if (suhuAwal.equals("Kelvin")&& temp.equals("Celcius")){
            double k = Double.parseDouble(inputSuhu.getText());
            double c = (double)(k - 273);
            
            besaranAwal.setText(String.valueOf(k));
            satuanAwal.setText("°K");
            besaranKonversi.setText(String.valueOf(c));
            satuanKonversi.setText("°C");
        }
        if (suhuAwal.equals("Kelvin")&& temp.equals("Fahrenheit")){
            double k = Double.parseDouble(inputSuhu.getText());
            double f = (double)(9/5 * (k - 273) + 32);
            
            besaranAwal.setText(String.valueOf(k));
            satuanAwal.setText("°K");
            besaranKonversi.setText(String.valueOf(f));
            satuanKonversi.setText("°F");
        }
        if (suhuAwal.equals("Kelvin")&& temp.equals("Reamur")){
            double k = Double.parseDouble(inputSuhu.getText());
            double r = (double)(4/5 * (k - 273));
            
            besaranAwal.setText(String.valueOf(k));
            satuanAwal.setText("°K");
            besaranKonversi.setText(String.valueOf(r));
            satuanKonversi.setText("°R");
        }
        if (suhuAwal.equals("Kelvin")&& temp.equals("Kelvin") || suhuAwal.equals("Reamur")&& temp.equals("Reamur")||suhuAwal.equals("Celcius")&& temp.equals("Celcius")||suhuAwal.equals("Fahrenheit")&& temp.equals("Fahrenheit")){
            JOptionPane.showMessageDialog(this, "cannot convert in same temperature");
            System.exit(0);
        }
        jDialog1.setSize(480, 240);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_tblKonversiActionPerformed

    private void inputSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuhuActionPerformed

    private void tempAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempAwalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonverterTemperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonverterTemperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonverterTemperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonverterTemperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonverterTemperatur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel besaranAwal;
    private javax.swing.JLabel besaranKonversi;
    private javax.swing.JTextField inputSuhu;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulDialog;
    private javax.swing.JLabel labelCelcius;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelUbah;
    private javax.swing.JLabel labelsamadengan;
    private javax.swing.JLabel satuanAwal;
    private javax.swing.JLabel satuanKonversi;
    private javax.swing.JButton tblKonversi;
    private javax.swing.JComboBox<String> tempAwal;
    private javax.swing.JComboBox<String> temperatur;
    // End of variables declaration//GEN-END:variables
}
